## Features variabelen uitbreiden

In [1]:
# libraries importeren 
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# dataset inlezen 
df = pd.read_csv('C:\Amaryllis_school_documents\Jaar_20_21\DDB\ddb_prorail\DDB_Prorail\data\sap_storing_data_hu_project.csv', low_memory=False)

In [3]:
#Doel : en bepaald probleem op een bepaalde locatie op een bepaald tijdstip, een voorspelling te maken van de verwachte reparatietijd


#Belangrijke kolommen bepalen

# Geeft een goede definitie van de probleem 
#oorz_code : feature - nominaal 
#oorz_groep :feauture - nominaal 
#stm_prioriteit :feature - ordinaal 

# Deze kolom geven een duidelijke gebied waar de aannemer werkt.
#stm_contractgeb_mld of  stm_contractgeb_gst: C Gebied waar de aannemer werkt. - nominaal 
    # Definieer de speciefieke gebied waar de aannemer zit.
# geocode vallen in contract gebied , maar niet alle

# De tijdstip van een storing weergeven. 
# tijd van de melding 
data = df[['stm_oorz_groep', 'stm_oorz_code', 'stm_prioriteit','stm_contractgeb_mld','stm_contractgeb_gst','stm_sap_meldtijd', 'stm_aanntpl_dd','stm_aanntpl_tijd','stm_fh_ddt']].copy()

In [4]:
data.loc[:, 'reparatietijd'] = (pd.to_datetime(data['stm_fh_ddt']) -  pd.to_datetime(data.loc[:,'stm_aanntpl_dd']  +" "+ data['stm_aanntpl_tijd'])).dt.total_seconds().div(60)

In [5]:
data.head()

,stm_oorz_groep,stm_oorz_code,stm_prioriteit,stm_geo_gst,stm_km_van_gst,stm_km_tot_gst,stm_contractgeb_mld,stm_contractgeb_gst,stm_techn_gst,stm_sap_meldtijd,stm_aanntpl_dd,stm_aanntpl_tijd,stm_fh_ddt,reparatietijd
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ONR-RIB,133.0,9.0,624.0,0.0,0.0,NaN,81.0,S,09:00:00,NaN,00:00:00,02/01/2006 09:00:00,NaN
2,ONR-DERD,143.0,9.0,201.0,30200.0,0.0,NaN,37.0,B,12:35:00,NaN,00:00:00,02/01/2006 13:26:00,NaN
3,ONR-DERD,142.0,9.0,25.0,14000.0,0.0,NaN,32.0,B,16:40:00,NaN,00:00:00,02/01/2006 17:20:00,NaN
4,ONR-DERD,142.0,9.0,12.0,19819.0,0.0,NaN,35.0,B,22:30:00,NaN,00:00:00,02/01/2006 22:36:00,NaN

In [6]:
data = data.drop(['stm_aanntpl_dd','stm_aanntpl_tijd','stm_fh_ddt'], axis= 1)

We hebben te maken met een continu target variabel en categorical feature variabelen

In [11]:
#Features variabelen  2:
features = data[['stm_oorz_groep', 'stm_oorz_code', 'stm_prioriteit', 'stm_contractgeb_gst', 'stm_sap_meldtijd']]
features.head()

,stm_oorz_groep,stm_oorz_code,stm_prioriteit,stm_contractgeb_gst,stm_sap_meldtijd
0,NaN,NaN,NaN,NaN,NaN
1,ONR-RIB,133.0,9.0,81.0,09:00:00
2,ONR-DERD,143.0,9.0,37.0,12:35:00
3,ONR-DERD,142.0,9.0,32.0,16:40:00
4,ONR-DERD,142.0,9.0,35.0,22:30:00

Voor de tijd van de melding moeten de tijden worden afgerond naar uren.